public enum Reserved_Keywords {
    NOT, SQRT, OR, AND, EQ, GRT, SUB, MUL, DIV, NUM, VOID, BEGIN, END, HALT,PRINT, INPUT, IF, ELSE, GREEN, MAIN, TEXT, OPEN_BRACKET, CLOSE_BRACKET, OPEN_CURLY_BRACKET, CLOSE_CURLY_BRACKET, COMMA, EQUAL, SEMI_COLON
}
